"""add website link to Venue model

Revision ID: 601defb08701
Revises: 4607b30a43bd
Create Date: 2020-01-27 08:31:22.691625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601defb08701'
down_revision = '4607b30a43bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###
