"""empty message

Revision ID: 9306a8ef1810
Revises: fa726243e320
Create Date: 2020-01-22 15:12:01.024780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9306a8ef1810'
down_revision = 'fa726243e320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_facebook_link_key', 'Artist', type_='unique')
    op.drop_constraint('Artist_image_link_key', 'Artist', type_='unique')
    op.drop_constraint('Venue_facebook_link_key', 'Venue', type_='unique')
    op.drop_constraint('Venue_image_link_key', 'Venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Venue_image_link_key', 'Venue', ['image_link'])
    op.create_unique_constraint('Venue_facebook_link_key', 'Venue', ['facebook_link'])
    op.create_unique_constraint('Artist_image_link_key', 'Artist', ['image_link'])
    op.create_unique_constraint('Artist_facebook_link_key', 'Artist', ['facebook_link'])
    # ### end Alembic commands ###
