"""add UNIQUE constraints to Arist and Venue models

Revision ID: 98b31f8e6f94
Revises: deddfd032130
Create Date: 2020-01-22 11:45:02.802785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b31f8e6f94'
down_revision = 'deddfd032130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['facebook_link'])
    op.create_unique_constraint(None, 'Artist', ['name'])
    op.create_unique_constraint(None, 'Artist', ['phone'])
    op.create_unique_constraint(None, 'Artist', ['image_link'])
    op.create_unique_constraint(None, 'Venue', ['phone'])
    op.create_unique_constraint(None, 'Venue', ['name'])
    op.create_unique_constraint(None, 'Venue', ['image_link'])
    op.create_unique_constraint(None, 'Venue', ['facebook_link'])
    op.create_unique_constraint(None, 'Venue', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
