"""edit length of links

Revision ID: ac8955c38a64
Revises: 601defb08701
Create Date: 2020-01-29 07:53:00.521908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8955c38a64'
down_revision = '601defb08701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scientific_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_poisonous', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='plants_pkey')
    )
    # ### end Alembic commands ###
