"""add available_hours to Artist model

Revision ID: bbdba8c38059
Revises: 6c584bd74849
Create Date: 2020-02-06 06:54:14.244856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbdba8c38059'
down_revision = '6c584bd74849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_hours', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_hours')
    # ### end Alembic commands ###
